package nz.co.ethan.tsbbanking.common;

public enum ErrorCodes {

    ERROR,
    INTERNAL_ERROR,
    USER_NOT_FOUND,
    STAFF_NOT_FOUND,
    USER_EXISTS,
    CUSTOMER_NOT_FOUND,
    INVALID_ROLE,
    INVALID_CREDENTIALS,
    USERS_NOT_IN_SAME_CUSTOMER,
    VALIDATION_ERROR,
    ACCOUNT_TYPE_NOT_ALLOWED,
    ACCOUNT_NOT_FOND,
    TOO_MANY_REQUESTS,
    NO_VERIFIED_USER,
    NO_REFRESH_TOKEN,
    REFRESH_TOKEN_NOT_ALLOWED,
    PRIMARY_NOT_IN_BIND_LIST,
    NO_PLATFORM_ROLE,
    BAD_REQUEST,
    BIND_EXISTS,

    OPENING_BALANCE_NEGATIVE,
    OVERDRAFT_NEGATIVE,
    FORBIDDEN,
    INVALID_ACCOUNT_TYPE,
    ACCOUNT_NUMBER_CONFLICT,
    USER_ROLE_NOT_ALLOWED,
    NO_PERMISSION,
    DUPLICATE_BINDING;


    public String code() { return name(); }
}